"""Initial migration with proper foreign keys

Revision ID: d1b6c47e0d9a
Revises: 
Create Date: 2025-12-01 17:46:15.921723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b6c47e0d9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('extracted_intent', sa.JSON(), nullable=True),
    sa.Column('pattern_report_id', sa.String(), nullable=True),
    sa.Column('patterns_confirmed', sa.Boolean(), nullable=False),
    sa.Column('lead_report_id', sa.String(), nullable=True),
    sa.Column('leads_generated', sa.Boolean(), nullable=False),
    sa.Column('user_confirmations', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('companies_analyzed', sa.Integer(), nullable=False),
    sa.Column('analysis_duration', sa.Float(), nullable=False),
    sa.Column('patterns', sa.JSON(), nullable=False),
    sa.Column('total_patterns', sa.Integer(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('high_confidence_patterns', sa.Integer(), nullable=False),
    sa.Column('key_insights', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('pattern_report_id', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('leads_generated', sa.Integer(), nullable=False),
    sa.Column('analysis_duration', sa.Float(), nullable=False),
    sa.Column('leads', sa.JSON(), nullable=False),
    sa.Column('high_priority_leads', sa.Integer(), nullable=False),
    sa.Column('medium_priority_leads', sa.Integer(), nullable=False),
    sa.Column('low_priority_leads', sa.Integer(), nullable=False),
    sa.Column('average_quality_score', sa.Float(), nullable=False),
    sa.Column('pattern_coverage', sa.JSON(), nullable=False),
    sa.Column('key_insights', sa.JSON(), nullable=False),
    sa.Column('market_opportunities', sa.JSON(), nullable=False),
    sa.Column('recommended_approach', sa.Text(), nullable=True),
    sa.Column('export_formats', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_report_id'], ['pattern_reports.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pattern_report_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=False),
    sa.Column('success_metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_report_id'], ['pattern_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_report_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('matched_patterns', sa.JSON(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_report_id'], ['lead_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_data_id', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('signal_metadata', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_data_id'], ['lead_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_analysis')
    op.drop_table('lead_data')
    op.drop_table('success_patterns')
    op.drop_table('lead_reports')
    op.drop_table('pattern_reports')
    op.drop_table('sessions')
    # ### end Alembic commands ###
